export const ORDER_STATUS = {
  AWAITING_QUOTATION: 'AWAITING_QUOTATION',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  IN_PREFLIGHT: 'PREFLIGHT', // Fixed mapping
  PREFLIGHT: 'PREFLIGHT',
  IN_PRODUCTION: 'IN_PRODUCTION',
  QC_PENDING: 'QC_PENDING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const DELIVERY_STATUS = {
  PENDING: 'PENDING',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  RETURNED: 'RETURNED',
} as const;

export const PROOF_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
